const adminStyle = document.createElement('link'); adminStyle.rel = 'stylesheet'; adminStyle.href = 'admin-extra.css'; document.head.appendChild(adminStyle);
const paypalAdminScript = document.createElement('script'); paypalAdminScript.src = '/admin-paypal.js?v=2'; document.head.appendChild(paypalAdminScript);
const keyInput = document.getElementById('adminKey');
const loginStatus = document.getElementById('loginStatus');
const board = document.getElementById('workflowBoard');
const metrics = document.getElementById('metrics');
const attentionList = document.getElementById('attentionList');
const filterSelect = document.getElementById('stageFilter');
let activeAdminKey = '';
let leads = [];
let stages = {};
const escapeHtml = value => String(value || '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const formatDate = value => value ? new Date(value).toLocaleString() : 'Not scheduled';
const stageOptions = selected => Object.entries(stages).map(([key, item]) => `<option value="${key}"${key === selected ? ' selected' : ''}>${escapeHtml(item.label)}</option>`).join('');
const previewUrl = lead => lead.previewUrl || (lead.preview?.siteSlug ? `/preview.html?site=${encodeURIComponent(lead.preview.siteSlug)}` : '');

function renderMetrics(analytics) {
  const totals = analytics.totals || {};
  const manual = leads.filter(lead => lead.workflow?.manual).length;
  const active = leads.filter(lead => !['closed','live','maintenance'].includes(lead.workflow?.stage)).length;
  metrics.innerHTML = [['Manual attention',manual],['Active customers',active],['Previews',totals.preview_created],['Enquiries',leads.length],['Live / managed',leads.filter(lead => ['live','maintenance'].includes(lead.workflow?.stage)).length]].map(([label,value]) => `<div class="metric"><strong>${value || 0}</strong><span>${label}</span></div>`).join('');
}
function renderAttention() {
  const waiting = leads.filter(lead => lead.workflow?.manual);
  attentionList.innerHTML = waiting.length ? waiting.map(lead => `<a href="#lead-${escapeHtml(lead.id)}"><strong>${escapeHtml(lead.practice)}</strong><span>${escapeHtml(lead.workflow.label)} · ${escapeHtml(lead.workflow.nextAction)}</span></a>`).join('') : '<p class="all-clear">✓ No customer currently needs manual feedback.</p>';
}
function renderBoard() {
  const visible = filterSelect.value === 'all' ? leads : leads.filter(lead => lead.workflow?.stage === filterSelect.value);
  board.innerHTML = visible.length ? visible.map(lead => {
    const workflow = lead.workflow || {}; const link = previewUrl(lead); const isFreeLive = lead.package === 'Free Live Website';
    const onboarding = lead.preview?.onboarding || {};
    const onboardingBlock = Object.keys(onboarding).length ? `<details class="onboarding-details"><summary>View onboarding details</summary><div class="customer-grid"><div><small>Domain</small><strong>${escapeHtml(onboarding.domain || 'Not decided')}</strong><p>${escapeHtml(onboarding.ownerName)}${onboarding.qualifications ? ` · ${escapeHtml(onboarding.qualifications)}` : ''}</p></div><div><small>Practice setup</small><strong>${escapeHtml(onboarding.hours || 'Hours not provided')}</strong><p>${escapeHtml(onboarding.address)}</p><p>${escapeHtml(onboarding.businessWhatsapp)}</p></div><div><small>Services and assets</small><p>${escapeHtml(onboarding.services)}</p>${onboarding.assetsUrl ? `<a href="${escapeHtml(onboarding.assetsUrl)}" target="_blank" rel="noopener">Open supplied assets ↗</a>` : '<p>No assets supplied</p>'}</div></div></details>` : '';
    const statusLink = workflow.customerToken ? `/status.html?token=${encodeURIComponent(workflow.customerToken)}` : '';
    const quoteBlock = `<section class="quote-controls"><div><small>Billing location</small><select class="billing-region" data-id="${escapeHtml(lead.id)}"><option value="">Confirm location</option><option value="IN"${workflow.billingRegion === "IN" ? " selected" : ""}>India</option><option value="OVERSEAS"${workflow.billingRegion === "OVERSEAS" ? " selected" : ""}>Outside India</option></select></div><div><small>Quotation currency</small><select class="quote-currency" data-id="${escapeHtml(lead.id)}">${["INR","USD","GBP","EUR"].map(code => `<option value="${code}"${code === (workflow.quoteCurrency || lead.preview?.currency || "INR") ? " selected" : ""}>${code}</option>`).join("")}</select></div><div><small>Final quotation amount</small><input class="quote-amount" data-id="${escapeHtml(lead.id)}" inputmode="decimal" placeholder="9999.00" value="${escapeHtml(workflow.quoteAmount)}"></div><label><small>India-only payment instructions</small><textarea class="payment-instructions" data-id="${escapeHtml(lead.id)}" rows="2" placeholder="UPI ID or Indian bank-transfer instructions. Overseas customers automatically receive PayPal instructions.">${escapeHtml(workflow.paymentInstructions)}</textarea></label><button class="send-quote" data-id="${escapeHtml(lead.id)}">Save and email customer</button></section>`;
    const approvalBlock = `<section class="approval-controls"><div><small>Final website preview URL</small><input class="final-preview-url" data-id="${escapeHtml(lead.id)}" placeholder="https://..." value="${escapeHtml(workflow.finalPreviewUrl || link)}"></div><button class="send-approval" data-id="${escapeHtml(lead.id)}">Send for customer approval</button>${workflow.revisionFeedback ? `<div class="revision-note"><small>Customer revisions</small><strong>${escapeHtml(workflow.revisionFeedback)}</strong></div>` : ''}${workflow.contentApprovedAt ? `<div class="approved-note">✓ Approved ${formatDate(workflow.contentApprovedAt)}</div>` : ''}</section>`;
    const checklist=workflow.launchChecklist||{}; const launchItems=[['domain','Domain ownership'],['dns','DNS connected'],['ssl','SSL active'],['contact','Phone and WhatsApp'],['forms','Forms tested'],['analytics','Analytics connected'],['approval','Approval recorded'],['verification','Business verified']];
    const launchBlock = `<details class="launch-controls"${workflow.stage==='launch_setup'?' open':''}><summary>Launch checklist</summary><div class="checklist">${launchItems.map(([key,label])=>`<label><input type="checkbox" class="launch-check" data-id="${escapeHtml(lead.id)}" data-key="${key}"${checklist[key]?' checked':''}> ${label}</label>`).join('')}</div><label>Live website URL<input class="live-url" data-id="${escapeHtml(lead.id)}" placeholder="https://customer-domain.com" value="${escapeHtml(workflow.liveUrl)}"></label><div class="launch-actions"><button class="save-launch" data-id="${escapeHtml(lead.id)}">Save checklist</button><button class="mark-live" data-id="${escapeHtml(lead.id)}">Mark live and email customer</button></div></details>`;
    const freePublishBlock = `<section class="free-publish-controls"><div><small>Free website publication</small><strong>${workflow.liveUrl ? 'Published on NiroLife' : 'Manual verification required'}</strong><p>${workflow.liveUrl ? `<a href="${escapeHtml(workflow.liveUrl)}" target="_blank" rel="noopener">${escapeHtml(workflow.liveUrl)} ↗</a>` : 'Confirm all three checks. Publishing creates the permanent NiroLife address and emails the customer.'}</p></div>${workflow.liveUrl ? '' : `<div class="free-checklist"><label><input type="checkbox" class="free-check" data-id="${escapeHtml(lead.id)}" data-key="identity"> Healthcare business and authority verified</label><label><input type="checkbox" class="free-check" data-id="${escapeHtml(lead.id)}" data-key="contact"> Phone, WhatsApp and address checked</label><label><input type="checkbox" class="free-check" data-id="${escapeHtml(lead.id)}" data-key="content"> Public content and claims reviewed</label></div><button class="publish-free" data-id="${escapeHtml(lead.id)}">Publish free website and email customer</button>`}</section>`;
    return `<article class="customer-card ${workflow.manual ? 'needs-attention' : ''}" id="lead-${escapeHtml(lead.id)}"><header><div><span class="owner owner-${escapeHtml(workflow.owner)}">${workflow.manual ? 'Action needed' : escapeHtml(workflow.owner || 'automation')}</span><h2>${escapeHtml(lead.practice)}</h2><p>${escapeHtml(lead.type)} · ${escapeHtml(lead.specialty)} · ${escapeHtml(lead.city)}</p></div><time>${formatDate(lead.createdAt)}</time></header><div class="journey"><div><small>Current stage</small><select class="stage-select" data-id="${escapeHtml(lead.id)}">${stageOptions(workflow.stage)}</select></div><div class="next-action"><small>What happens next</small><strong>${escapeHtml(workflow.nextAction)}</strong></div></div><div class="customer-grid"><div><small>Customer</small><strong>${escapeHtml(lead.contactName)}</strong><a href="mailto:${escapeHtml(lead.email)}">${escapeHtml(lead.email)}</a><a href="tel:${escapeHtml(lead.phone)}">${escapeHtml(lead.phone)}</a></div><div><small>Selected offer</small><strong>${escapeHtml(lead.package)}</strong><p>${escapeHtml(lead.message)}</p></div><div><small>Follow-up</small><input class="follow-up" data-id="${escapeHtml(lead.id)}" type="datetime-local" value="${escapeHtml(workflow.followUpAt ? workflow.followUpAt.slice(0,16) : '')}"><button class="save-follow-up" data-id="${escapeHtml(lead.id)}">Save reminder</button></div></div>${onboardingBlock}${isFreeLive ? freePublishBlock : `${quoteBlock}${approvalBlock}${launchBlock}`}<label class="notes-label">Internal notes<textarea class="notes" data-id="${escapeHtml(lead.id)}" placeholder="Add decisions, customer feedback or setup details…">${escapeHtml(workflow.notes)}</textarea></label><footer><div>${link ? `<a class="preview-link" href="${escapeHtml(link)}" target="_blank" rel="noopener">Open customer website ↗</a>` : '<span class="muted">Preview link unavailable for older enquiry</span>'}${statusLink ? `<a class="status-link" href="${escapeHtml(statusLink)}" target="_blank" rel="noopener">Open customer portal ↗</a>` : ''}</div><button class="save-notes" data-id="${escapeHtml(lead.id)}">Save notes</button></footer></article>`;
  }).join('') : '<div class="empty">No customers in this stage.</div>';
  bindActions();
}
async function updateLead(id, changes, button) {
  if (button) button.disabled = true;
  try { const response = await fetch(`/api/admin/enquiries/${encodeURIComponent(id)}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', 'x-admin-key': activeAdminKey }, body: JSON.stringify(changes) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Update failed.'); const lead = leads.find(item => String(item.id) === String(id)); if (lead && result.workflow) lead.workflow = result.workflow; renderAttention(); renderBoard(); }
  catch (error) { loginStatus.textContent = error.message; } finally { if (button) button.disabled = false; }
}
function bindActions() {
  document.querySelectorAll('.stage-select').forEach(select => select.addEventListener('change', () => updateLead(select.dataset.id, { workflowStage: select.value }, select)));
  document.querySelectorAll('.save-notes').forEach(button => button.addEventListener('click', () => { const notes = document.querySelector(`.notes[data-id="${CSS.escape(button.dataset.id)}"]`).value; updateLead(button.dataset.id, { workflowStage: leads.find(item => String(item.id) === String(button.dataset.id)).workflow.stage, notes }, button); }));
  document.querySelectorAll('.save-follow-up').forEach(button => button.addEventListener('click', () => { const followUpAt = document.querySelector(`.follow-up[data-id="${CSS.escape(button.dataset.id)}"]`).value; updateLead(button.dataset.id, { workflowStage: leads.find(item => String(item.id) === String(button.dataset.id)).workflow.stage, followUpAt }, button); }));
  document.querySelectorAll('.send-quote').forEach(button => button.addEventListener('click', () => { const id=button.dataset.id; const quoteAmount=document.querySelector(`.quote-amount[data-id="${CSS.escape(id)}"]`).value; const quoteCurrency=document.querySelector(`.quote-currency[data-id="${CSS.escape(id)}"]`).value; const billingRegion=document.querySelector(`.billing-region[data-id="${CSS.escape(id)}"]`).value; const paymentInstructions=document.querySelector(`.payment-instructions[data-id="${CSS.escape(id)}"]`).value; if(!quoteAmount){loginStatus.textContent='Enter the final quotation before emailing the customer.';return;} if(!billingRegion){loginStatus.textContent='Confirm whether the customer is in India or overseas.';return;} if((billingRegion==='IN'&&quoteCurrency!=='INR')||(billingRegion==='OVERSEAS'&&quoteCurrency==='INR')){loginStatus.textContent='India quotes use INR; overseas PayPal quotes use USD, GBP or EUR.';return;} if(billingRegion==='IN'&&!paymentInstructions.trim()){loginStatus.textContent='Add the India-only UPI or bank-transfer instructions.';return;} updateLead(id,{workflowStage:'payment_review',quoteAmount,quoteCurrency,billingRegion,paymentInstructions,notifyCustomer:true},button); }));
  document.querySelectorAll('.send-approval').forEach(button => button.addEventListener('click', () => { const id=button.dataset.id; const finalPreviewUrl=document.querySelector(`.final-preview-url[data-id="${CSS.escape(id)}"]`).value.trim(); if(!finalPreviewUrl){loginStatus.textContent='Add the final preview URL first.';return;} updateLead(id,{workflowStage:'content_approval',finalPreviewUrl,notifyCustomer:true},button); }));
  const launchData=id=>{const launchChecklist={};document.querySelectorAll(`.launch-check[data-id="${CSS.escape(id)}"]`).forEach(input=>launchChecklist[input.dataset.key]=input.checked);const liveUrl=document.querySelector(`.live-url[data-id="${CSS.escape(id)}"]`).value.trim();return{launchChecklist,liveUrl};};
  document.querySelectorAll('.save-launch').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.id;const lead=leads.find(item=>String(item.id)===String(id));updateLead(id,{workflowStage:lead.workflow.stage,...launchData(id)},button);}));
  document.querySelectorAll('.mark-live').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.id;updateLead(id,{workflowStage:'live',...launchData(id),notifyCustomer:true},button);}));
  document.querySelectorAll('.publish-free').forEach(button=>button.addEventListener('click',async()=>{const id=button.dataset.id;const checks={};document.querySelectorAll(`.free-check[data-id="${CSS.escape(id)}"]`).forEach(input=>checks[input.dataset.key]=input.checked);if(!['identity','contact','content'].every(key=>checks[key])){loginStatus.textContent='Complete all three free website verification checks.';return;}button.disabled=true;loginStatus.textContent='Publishing free website…';try{const response=await fetch(`/api/admin/enquiries/${encodeURIComponent(id)}/publish-free`,{method:'POST',headers:{'Content-Type':'application/json','x-admin-key':activeAdminKey},body:JSON.stringify({checks})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Publication failed.');const lead=leads.find(item=>String(item.id)===String(id));if(lead)lead.workflow=result.workflow;renderAttention();renderBoard();loginStatus.textContent='Free website published and customer email queued.';}catch(error){loginStatus.textContent=error.message;button.disabled=false;}}));
}
filterSelect.addEventListener('change', renderBoard);
document.getElementById('refreshButton').addEventListener('click', loadDashboard);
document.getElementById('loadButton').addEventListener('click', loadDashboard);
async function loadDashboard() {
  loginStatus.textContent = 'Loading…';
  try { activeAdminKey = keyInput.value || activeAdminKey; const headers = { 'x-admin-key': activeAdminKey }; const [leadResponse, analyticsResponse, stageResponse] = await Promise.all([fetch('/api/admin/enquiries', { headers }), fetch('/api/admin/analytics', { headers }), fetch('/api/admin/workflow-stages', { headers })]); const data = await leadResponse.json(); const analytics = await analyticsResponse.json(); stages = await stageResponse.json(); if (!leadResponse.ok) throw new Error(data.error || 'Unable to load customers.'); leads = data; document.getElementById('login').hidden = true; document.getElementById('dashboard').hidden = false; filterSelect.innerHTML = '<option value="all">All stages</option>' + stageOptions(''); renderMetrics(analytics); renderAttention(); renderBoard(); loginStatus.textContent = ''; }
  catch (error) { loginStatus.textContent = error.message; }
}
