const assert = require('node:assert/strict');
const render = require('./public-site-template');
const sample = {practice:'Harbour Dental Studio',specialty:'Dentistry',city:'Sydney',address:'12 George Street',hours:'Mon-Fri 8-6',phone:'+61 2 5555 0100',whatsapp:'61412345678',services:'Check-ups, Whitening',slug:'harbour-dental'};
const full = render(sample);
for (const section of ['id="services"','id="about"','id="visit"','id="contact"','public-faq','patient-mobile']) assert.ok(full.includes(section),section);
assert.ok(full.includes('tel:+61255550100'));
assert.ok(full.includes('https://wa.me/61412345678'));
assert.ok(!full.includes('addressCountry'));
const minimal = render({practice:'Care Practice',slug:'care'});
assert.ok(!minimal.includes('id="services"'));
assert.ok(!minimal.includes('public-faq'));
assert.ok(!minimal.includes('https://wa.me/'));
assert.ok(!minimal.includes('tel:'));
assert.ok(!minimal.includes('undefined'));
const phoneOnly = render({...sample,whatsapp:''});
assert.ok(!phoneOnly.includes('https://wa.me/'));
assert.ok(phoneOnly.includes('href="tel:+61255550100"'));
const hostile = render({...sample,practice:'<script>alert(1)</script>',bio:'</script><img src=x onerror=alert(1)>'});
assert.ok(!hostile.includes('<script>alert(1)</script>'));
assert.ok(!hostile.includes('<img src=x'));
assert.ok(hostile.includes('\\u003c'));
console.log('Passed: full, minimal, phone-only, international and HTML-injection cases.');
for(const template of ['modern','premium','minimal']) assert.ok(render({...sample,template}).includes(`template-${template}`));
assert.ok(render({...sample,heroStyle:'illustration'}).includes('src="/healthcare-website-design.svg"'));
assert.ok(render({...sample,heroStyle:'photo'}).includes('Illustrative healthcare image'));
assert.ok(render({...sample,photo:'data:image/png;base64,YQ=='}).includes('src="data:image/png;base64,YQ=="'));
assert.ok(!render({...sample,photo:'javascript:alert(1)'}).includes('javascript:'));
console.log('Passed: template choices, illustration, labelled photo, uploaded photo and unsafe image rejection.');
